cwt.Config.createConfig("weatherMinDays",1,5,1);
cwt.Config.createConfig("weatherRandomDays",0,5,4);
cwt.Config.createConfig("round_dayLimit",0,999,0);
cwt.Config.createConfig("noUnitsLeftLoose",0,1,0);
cwt.Config.createConfig("autoSupplyAtTurnStart",0,1,1);
cwt.Config.createConfig("unitLimit",0,cwt.MAX_UNITS,0,5);
cwt.Config.createConfig("captureLimit",0,cwt.MAX_PROPERTIES,0);
cwt.Config.createConfig("timer_turnTimeLimit",0,60,0,1);
cwt.Config.createConfig("timer_gameTimeLimit",0,99999,0,5);
cwt.Config.createConfig("co_getStarCost", 100, 50000, 9000, 100);
cwt.Config.createConfig("co_getStarCostIncrease", 0, 50000, 1800, 100);
cwt.Config.createConfig("co_getStarCostIncreaseSteps", 0, 50, 10);
cwt.Config.createConfig("co_enabledCoPower", 0, 1, 1);
cwt.Config.createConfig("fogEnabled", 0, 1, 1);
cwt.Config.createConfig("daysOfPeace", 0, 50, 0);
