package org.wolftec.cwtactics.game.state.system;

import org.stjs.javascript.Date;
import org.stjs.javascript.dom.Form;
import org.stjs.javascript.dom.Input;
import org.wolftec.cwtactics.game.renderer.UserInterfaceLayerBean;
import org.wolftec.wCore.core.BrowserUtil;
import org.wolftec.wCore.core.Injected;
import org.wolftec.wCore.core.ManagedComponent;
import org.wolftec.wCore.core.ManagedConstruction;
import org.wolftec.wCore.log.Logger;
import org.wolftec.wCore.persistence.VirtualFilesystemManager;
import org.wolftec.wPlay.state.MenuState;
import org.wolftec.wPlay.state.StateManager;

@ManagedComponent
public class ErrorState extends MenuState {

  // TODO by config
  public static final String ERROR_FORM_URL = "http://battle.customwars.com/report/index.php";

  @ManagedConstruction
  private Logger log;

  @Injected
  private UserInterfaceLayerBean ui;

  @Injected
  private VirtualFilesystemManager vfs;

  private String errorMessage;

  @Override
  public void createLayout(StateManager stm) {
    // TODO

    createActionButton(root, null, "menu.error.sendReport", "20% 70% 20% 20%", () -> {
      sendErrorReport();
      BrowserUtil.reloadCurrentURL();
    });

    createActionButton(root, null, "menu.error.cleanData", "40% 70% 20% 20%", () -> {
      vfs.purgeKeys(null, (err) -> {
        BrowserUtil.reloadCurrentURL();
      });
    });

    createActionButton(root, null, "menu.error.reload", "60% 70% 20% 20%", () -> {
      BrowserUtil.reloadCurrentURL();
    });
  }

  public void setErrorMessage(String message) {
    this.errorMessage = message;
  }

  @Override
  public void enter(StateManager stm) {
    errorMessage = "";
  }

  private void sendErrorReport() {
    Form form = BrowserUtil.createDomElement("form");
    Input inputMsg = BrowserUtil.createDomElement("input");
    Input inputTitle = BrowserUtil.createDomElement("input");

    inputMsg.name = "problem";
    inputMsg.value = errorMessage;

    inputTitle.name = "title";
    inputTitle.value = "Autogenerated Error Report " + (new Date()).getTime();

    form.action = "post";
    form.target = ERROR_FORM_URL;
    form.appendChild(inputTitle);
    form.appendChild(inputMsg);

    form.submit();
  }
}
