package org.wolftec.cwtactics.game.state.system;

import org.stjs.javascript.Date;
import org.stjs.javascript.dom.Form;
import org.stjs.javascript.dom.Input;
import org.wolftec.cwtactics.game.renderer.UserInterfaceLayerBean;
import org.wolftec.wCore.core.BrowserUtil;
import org.wolftec.wCore.core.ComponentManager;
import org.wolftec.wCore.core.Injected;
import org.wolftec.wCore.core.ManagedComponent;
import org.wolftec.wCore.core.ManagedComponentInitialization;
import org.wolftec.wCore.core.ManagedConstruction;
import org.wolftec.wCore.log.Logger;
import org.wolftec.wPlay.gui.UiContainer;
import org.wolftec.wPlay.state.State;
import org.wolftec.wPlay.state.StateManager;

@ManagedComponent
public class ErrorState implements State, ManagedComponentInitialization {

  // TODO by config
  public static final String ERROR_FORM_URL = "http://battle.customwars.com/report/index.php";

  // TODO use button group

  private UiContainer p_container;

  @ManagedConstruction
  private Logger log;

  @Injected
  private UserInterfaceLayerBean ui;

  private String errorMessage;
  private boolean rendered;

  private int selectedAction;

  @Override
  public void onComponentConstruction(ComponentManager manager) {
    p_container = new UiContainer(null);

  }

  public void setErrorMessage(String message) {
    this.errorMessage = message;
  }

  @Override
  public void enter(StateManager stm) {
    rendered = false;
    errorMessage = "";
    selectedAction = 0;

    String pressedAction = null;

    if (pressedAction == "SEND") {
      sendErrorReport();
    }
  }

  @Override
  public void render(int delta) {
    p_container.draw(ui);
  }

  private void sendErrorReport() {
    Form form = BrowserUtil.createDomElement("form");
    Input inputMsg = BrowserUtil.createDomElement("input");
    Input inputTitle = BrowserUtil.createDomElement("input");

    inputMsg.name = "problem";
    inputMsg.value = errorMessage;

    inputTitle.name = "title";
    inputTitle.value = "Autogenerated Error Report " + (new Date()).getTime();

    form.action = "post";
    form.target = ERROR_FORM_URL;
    form.appendChild(inputTitle);
    form.appendChild(inputMsg);

    form.submit();
  }
}
