export const MAX_MAP_WIDTH = 32

export const MAX_MAP_HEIGHT = 32

export const MAX_PLAYERS = 4

export const MAX_UNITS_PER_PLAYER = 50

export const TILE_SIDE_LENGTH = 16

export const SCREEN_WIDTH = TILE_SIDE_LENGTH * 20 

export const SCREEN_HEIGHT = TILE_SIDE_LENGTH * 15 

export const SCREEN_SCALE_FACTOR = 2

export const UNSTABLE_PERFORMANCE_RELATED_TO_AVERAGE_DURATION_FACTOR = 2