package net.temp.cwt.game.states.generic;

import net.temp.cwt.game.renderer.beans.UserInterfaceLayerBean;
import net.temp.wolfTecEngine.logging.Logger;
import net.temp.wolfTecEngine.renderer.gui.UiContainer;
import net.temp.wolfTecEngine.statemachine.State;
import net.temp.wolfTecEngine.statemachine.StateManager;

import org.stjs.javascript.Date;
import org.stjs.javascript.dom.Form;
import org.stjs.javascript.dom.Input;
import org.wolftec.core.BrowserUtil;
import org.wolftec.core.ComponentManager;
import org.wolftec.core.Injected;
import org.wolftec.core.ManagedComponent;
import org.wolftec.core.ManagedComponentInitialization;
import org.wolftec.core.ManagedConstruction;

@ManagedComponent
public class ErrorState implements State, ManagedComponentInitialization {

  // TODO by config
  public static final String ERROR_FORM_URL = "http://battle.customwars.com/report/index.php";

  // TODO use button group

  private UiContainer p_container;
  
  @ManagedConstruction
  private Logger log;

  @Injected
  private UserInterfaceLayerBean ui;

  private String errorMessage;
  private boolean rendered;

  private int selectedAction;
  
  @Override
  public void onComponentConstruction(ComponentManager manager) {
    p_container = new UiContainer();
    
  }

  public void setErrorMessage(String message) {
    this.errorMessage = message;
  }

  @Override
  public void enter(StateManager stm) {
    rendered = false;
    errorMessage = "";
    selectedAction = 0;
   
    String pressedAction = null;
    
    if(pressedAction == "SEND") {
      sendErrorReport();
    }
  }
  
  @Override
  public void render(int delta) {
    p_container.draw(ui);
  }

  private void sendErrorReport() {
    Form form = BrowserUtil.createDomElement("form");
    Input inputMsg = BrowserUtil.createDomElement("input");
    Input inputTitle = BrowserUtil.createDomElement("input");

    inputMsg.name = "problem";
    inputMsg.value = errorMessage;

    inputTitle.name = "title";
    inputTitle.value = "Autogenerated Error Report " + (new Date()).getTime();

    form.action = "post";
    form.target = ERROR_FORM_URL;
    form.appendChild(inputTitle);
    form.appendChild(inputMsg);
    
    form.submit();
  }
}
