cwt.Localization.registerLang({
  "INFT": "Infantry",
  "MECH": "Mech. Infantry",
  "TNTK": "Tank",
  "NTNK": "Neotank",
  "MDTK": "Md. Tank",
  "WRTK": "War Tank",
  "ARTY": "Artillery",
  "RCKT": "Rocket Launcher",
  "RECN": "Recon",
  "BIKE": "Bike",
  "AAIR": "Anti-Air",
  "APCR": "APC",
  "MISS": "Missiles",
  "BCTR": "Battle Copter",
  "BMBR": "Bomber",
  "BKBM": "Black Bomb",
  "TCTR": "Transport Copter",
  "FGTR": "Fighter",
  "STLH": "Stealth",
  "SEAP": "Seaplane",
  "SUBM": "Submarine",
  "CRUS": "Cruiser",
  "ACAR": "Aircraft Carrier",
  "LNDR": "Lander",
  "BSHP": "Battleship",

  "PLIN": "Plain",
  "MNTN": "Mountain",
  "FRST": "Forrest",

  "ROAD": "Road",
  "BASE": "Base",
  "HQTR": "Headquarter",
  "BHMCE": "Mini-Cannon (East)",
  "BHMCN": "Mini-Cannon (Nord)",
  "BHMCS": "Mini-Cannon (South)",
  "BHMCW": "Mini-Cannon (West)",
  "PQRT": "SeaPort",
  "APRT": "Airport",

  "CTPR": "Capture Property",
  "UNUN": "Unload Unit",
  "LODU": "Load Unit",
  "NXTR": "End Turn",
  "WTUN": "Wait",
  "JNUN": "Join",
  "subWeapon": "Sub Weapon",
  "mainWeapon": "Main Weapon",
  "SLFR": "Launch Rocket",
  "GMTP": "Send Money to Player",
  "GPTP": "Send Property to Player",
  "GUTP": "Send Unit to Player",
  "SPPL": "Supply",
  "ATUN": "Attack",
  "BDUN": "Build Unit",
  "HIUN": "Hide Unit",
  "UHUN": "Unhide Unit",
  "ANCP": "Activate CO Power",
  "ASCP": "Activate Co Super Power",
  "yes": "Yes",
  "no": "No",
  "ok": "Ok",
  "left": "Left",
  "right": "Right",
  "up": "Up",
  "down": "Down",
  "action": "Action",
  "cancel": "Cancel",
  "done": "Done",
  "day": "Day",
  "propertyCaptured": "The property was captured",
  "propertyPointsLeft": "Property capturing... Left points:",
  "capturePoints": "Property Points",
  "defense": "Tile Defense",
  "health": "Health",
  "ammo": "Ammo",
  "fuel": "Fuel",
  "weatherChange": "Weather changes to",
  "SUN": "Sun",
  "RAIN": "Rain",
  "SNOW": "Snow",
  "gameHasEnded": "The game has ended because only one team is left",

  "activatePower": "Activate Power",
  "cop": "Co Power",
  "scop": "Super Co Power",
  "attack": "Attack",
  "buildUnit": "Build",
  "capture": "Capture",
  "transferMoney": "Transfer Money",
  "transferProperty": "Transfer Property",
  "transferUnit": "Transfer Unit",
  "hideUnit": "Hide",
  "unhideUnit": "Unhide",
  "joinUnits": "Join",
  "loadUnit": "Load",
  "unloadUnit": "Unload",
  "nextTurn": "End Turn",
  "silofire": "Fire Silo",
  "supplyUnit": "Supply",
  "wait": "Wait",
  "doExplosion": "Explode",

  "loading.loadMaps": "Loading Maps",
  "loading.loadImages": "Loading Images",
  "loading.cropImages": "Cropping Images",
  "loading.colorizeImages": "Colorize Images",
  "loading.loadSounds": "Loading Sounds",
  "loading.prepareInput": "Preparing Input Systems",
  "loading.prepareLanguage": "Localize Strings",
  "loading.done": "Complete",

  "menu.header": "Menu",
  "menu.version": "Version",

  "player": "Player",

  "config.type.prev": "<<",
  "config.type.next": ">>",
  "config.co.prev": "<<",
  "config.co.next": ">>",
  "config.team.next": ">>",
  "config.team.prev": "<<",

  "config.playerCo": "CO",
  "config.playerType": "Type",
  "config.playerTeam": "Team",

  "config.next": "Start Game",

  "config.player.off": "Free",
  "config.player.disabled": "-",
  "config.player.co.none": "None",
  "config.player.AI": "AI",
  "config.player.human": "Human",

  "message.panel.header": "Message",

  "versus.playerconfig": "Player Configuration",
  "versus.mapSelection": "Select Map",
  "versus.next": "Game Configuration",
  "versus.prevMap": "Previous Map",
  "versus.nextMap": "Next Map",

  "error.panel.action": "Reset Game-Data?",
  "error.panel.header": "Fatal Error",
  "error.panel.reason": "Reason",
  "error.panel.data": "Data",
  "error.panel.no": "No",
  "error.panel.yes": "Yes",

  "MAIN_MENU_OPTIONS": "Options",
  "MAIN_MENU_NETWORK": "Network Game",
  "MAIN_MENU_SKIRMISH": "Singleplayer",
  "MAIN_MENU_TEST_WEATHER": "Weather-Test",

  "OPTIONS_SFX_VOL_DOWN": "-",
  "OPTIONS_SFX_VOL_UP": "+",
  "OPTIONS_MUSIC_VOL_DOWN": "-",
  "OPTIONS_MUSIC_VOL_UP": "+",
  "OPTIONS_CHECKBOX_ANIMATED_TILES_TEXT": "Animated Tiles",
  "OPTIONS_CHECKBOX_FORCE_TOUCH_TEXT": "Force Touch Controls",
  "OPTIONS_MENU_CHANGE_KEYBOARD_LAYOUT": "Remap Keyboard",
  "OPTIONS_MENU_CHANGE_GAMEPAD_LAYOUT": "Remap Gamepad",
  "OPTIONS_MENU_WIPE_OUT": "Reset Data",
  "OPTIONS_MENU_GO_BACK": "Go Back",

  "OPTIONS_WIPE_OUT_TEXT": "Do you want to erase all game data? The game\ndata will be downloaded during the next start\nof the game.",
  "OPTIONS_WIPE_OUT_NO": "Cancel",
  "OPTIONS_WIPE_OUT_YES": "Do It",

  "OPTIONS_KEYMAP_RIGHT": "Right",
  "OPTIONS_KEYMAP_LEFT": "Left",
  "OPTIONS_KEYMAP_DOWN": "Down",
  "OPTIONS_KEYMAP_UP": "Up",
  "OPTIONS_KEYMAP_ACTION": "Action",
  "OPTIONS_KEYMAP_CANCEL": "Cancel",

  "MAP_SELECT_PAGE_LEFT": "<<",
  "MAP_SELECT_PAGE": "",
  "MAP_SELECT_PAGE_RIGHT": ">>",
  "MENU_BACK": "Back",
  "MENU_RIGHT": ">>",
  "MENU_LEFT": "<<",
  "MENU_NEXT": "Next",
  "MENU_CONFIGURED_MATCH": "Configured Match",
  "MENU_FAST_MATCH": "Fast Match",

  "PLAYER_CONFIG_SLOT1": "Slot 1",
  "PLAYER_CONFIG_SLOT2": "Slot 2",
  "PLAYER_CONFIG_SLOT3": "Slot 3",
  "PLAYER_CONFIG_SLOT4": "Slot 4",

  "PLAYER_CONFIG_NAME": "Name",
  "PLAYER_CONFIG_TYPE": "Type",
  "PLAYER_CONFIG_TEAM": "Team",
  "PLAYER_CONFIG_CO_A": "Main CO",
  "PLAYER_CONFIG_GAMEMODE": "Gamemode",

  "VALUE_R": "",
  "VALUE_L": "",
  "VALUE_U": "",
  "VALUE_D": "",
  "VALUE_A": "",
  "VALUE_C": "",

  "co_getStarCost": "Star Costs",
  "co_getStarCostIncrease": "Star Costs Increase",
  "co_getStarCostIncreaseSteps": "Star C. Incr. Steps",
  "co_enabledCoPower": "Co Powers",
  "fogEnabled": "Fog Mode",
  "daysOfPeace": "Days of Peace",
  "weatherMinDays": "Weather min. duration",
  "weatherRandomDays": "Weather max. duration",
  "noUnitsLeftLoose": "Loose without units",
  "autoSupplyAtTurnStart": "Turn Start Auto-Supply",
  "round_dayLimit": "Day limit",
  "unitLimit": "Unit Limit",
  "captureLimit": "Capture Limit",
  "timer_turnTimeLimit": "Turn Time (Min.)",
  "timer_gameTimeLimit": "Game Time (Min.)",

  "OPTIONS_KEYMAP_GOBACK": "Go Back",
  "OPTIONS_KEYMAP_SET": "Remap Keys",

  "TOOLTIP_1": "Change the keyboard and gamepad settings by selecting\nOptions from the main or in-game menu",
  "TOOLTIP_2": "Activate zooming the map by using the scroll wheel for\nthe mouse, pinching for touch screen, and the in-game menu.",
  "TOOLTIP_3": "Press and hold Cancel over an idle unit to see\nits attack range.",
  "TOOLTIP_4": "Perform Cancel by right-clicking with mouse, or\ndouble-tapping for touch screen.",
  "TOOLTIP_5": "Keyboard and game-pad controls can be changed via\nthe Options Menu.",
  "TOOLTIP_6": "Perform Action by lieft-clicking with the mouse,\nor tapping the touch screen.",
  "TOOLTIP_7": "Reporting bugs to the developers can be done\nthrough the Mailing List or the forum.",
  "TOOLTIP_8": "Custom Wars Tactics concept started in January 2009.\nThe original name for the project was called 'Tactic Wars'.",
  "TOOLTIP_9": "Custom Wars Tactics is playable from PC and also\nfrom mobile devices.",
  "TOOLTIP_10": "Custom Wars Tactics can be played offline in your\nbrowser. (As long you aren't in private browsing mode.)",
  "TOOLTIP_11": "A full desktop counterpart for Custom Wars Tactics\nis being developed. Stay tuned!"
});

/*
cwt.Localization.registerLang({
  "INFT": "Infanterie",
  "MECH": "Mech. Infanterie",
  "TNTK": "Leichter Panzer",
  "MDTK": "Kampfpanzer",
  "WRTK": "Schw. Panzer",
  "NTNK": "Neo Panzer",
  "ARTY": "Artillerie",
  "RCKT": "Raketenwerfer",
  "RECN": "Aufklärer",
  "BIKE": "Mot. Aufklärer",
  "AAIR": "Luftabwehr-Panzer",
  "APCR": "Versorgunsfahrz.",
  "MISS": "Luftabwehr-Raketenw.",
  "BCTR": "Kampfhubschrauber",
  "BMBR": "Bomber",
  "BKBM": "S-Bombe",
  "TCTR": "Transporthubschrauber",
  "FGTR": "Jet",
  "STLH": "Tarnkappenbomber",
  "SEAP": "Kampfjet",
  "SUBM": "U-Boot",
  "CRUS": "Kreuzer",
  "ACAR": "Flugzeugträger",
  "LNDR": "Transportboot",
  "BSHP": "Schlachtschiff",

  "PLIN": "Wiese",
  "MNTN": "Berg",
  "FRST": "Wald",

  "ROAD": "Straße",
  "BASE": "Fabrik",
  "HQTR": "Hauptquartiert",
  "BHMCE": "Mini-Kanone (Ost)",
  "BHMCN": "Mini-Kanone (Nord)",
  "BHMCS": "Mini-Kanone (Süd)",
  "BHMCW": "Mini-Kanone (West)",
  "PQRT": "Hafen",
  "APRT": "Flughafen",

  "CTPR": "Besetze Geb&auml;ude",
  "UNUN": "Einheit ausladen",
  "LODU": "Einheit einladen",
  "NXTR": "Beende Zug",
  "WTUN": "Warten",
  "JNUN": "Einheiten Vereinen",
  "subWeapon": "Zweitwaffe",
  "mainWeapon": "Hauptwaffe",
  "SLFR": "Rakete abfeuern",
  "GMTP": "Geld an Spieler abtreten",
  "GPTP": "Gebäude an Spieler abtreten",
  "GUTP": "Einheit an Spieler abtreten",
  "SPPL": "Einheiten Versorgen",
  "ATUN": "Angreifen",
  "BDUN": "Einheit produzieren",
  "HIUN": "Einheit tarnen",
  "UHUN": "Einheit enttarnen",
  "ANCP": "Co Kraft aktivieren",
  "ASCP": "Co Superkraft aktivieren",
  "CTPR.desc": "Besetzt das angegebene Geb&auml;ude. Wenn die Einheit die Eroberungspunkte dess Geb&auml;udes auf 0 senkt geht der Besitz auf den Eroberer &uuml;ber.",
  "UNUN.desc": "Die Einheit wird in den Transporter ausgeladen. Nach dem Ausladen k&ouml;nnen beide Einheitein keine Aktionen innerhalb des aktiven Zuges ausf&uuml;hren.",
  "LODU.desc": "Die Einheit wird in den Transporter eingeladen.",
  "NXTR.desc": "Beende Zug",
  "WTUN.desc": "Die Einheit beendet ihren Zug und kann danach innerhalb des aktiven Zuges nicht mehr benutzt werden.",
  "JNUN.desc": "Zwei Einheiten werden zu einer vereint und f&uuml;gen ihre vorhandenen Lebenspunkte und Ressourcen zusammen.",
  "subWeapon.desc": "Angriff mit der Zweitwaffe der Einheit.",
  "mainWeapon.desc": "Angriff mit der Hauptwaffe der Einheit.",
  "SLFR.desc": "Feuert eine Rakete auf ein Ziel ab welches mit einer Reichweite von 2 alle feindlichen Einheiten 2 HP Schaden zuf&uuml;gt.",
  "yes": "Ja",
  "no": "Nein",
  "ok": "Ok",
  "left": "Links",
  "right": "Rechts",
  "up": "Oben",
  "down": "Unten",
  "action": "Aktion",
  "cancel": "Abbrechen",
  "done": "Fertig",
  "day": "Tag",
  "propertyCaptured": "Das Gebäude wurde erobert",
  "propertyPointsLeft": "Das Gebäude wird erobert... Punkte übrig:",
  "capturePoints": "Basispunkte",
  "defense": "Feldverteidigung",
  "health": "Leben",
  "ammo": "Munition",
  "fuel": "Treibstoff",
  "weatherChange": "Wetter ändert sich zu",
  "SUN": "Sonnenschein",
  "RAIN": "Regen",
  "SNOW": "Schnee",
  "gameHasEnded": "Das Spiel ist vorbei, es existiert nur noch ein Team",

  "activatePower": "Aktiviere CO Kraft",
  "cop": "CO Power",
  "scop": "Super CO Power",
  "attack": "Angreifen",
  "buildUnit": "Bauen",
  "capture": "Erobern",
  "transferMoney": "Sende Geld",
  "transferProperty": "Sende Gebäude",
  "transferUnit": "Sende Einheit",
  "hideUnit": "Tarnen",
  "unhideUnit": "Enttarnen",
  "joinUnits": "Vereinen",
  "loadUnit": "Einladen",
  "unloadUnit": "Ausladen",
  "nextTurn": "Zug Beenden",
  "silofire": "Silo Abfeuer",
  "supplyUnit": "Versorgen",
  "wait": "Warten",
  "doExplosion": "Explodieren",

  "options": "Optionen",
  "options.sfx": "SFX An/Aus",
  "options.music": "Musik An/Aus",
  "options.yield": "Aufgeben",

  "loading.loadMaps": "Lade Karten",
  "loading.loadImages": "Lade Grafiken",
  "loading.cropImages": "Schneide Grafiken zu",
  "loading.colorizeImages": "Färbe Grafiken ein",
  "loading.loadSounds": "Lade Soundeffekte",
  "loading.prepareInput": "Initialisiere Eingabesysteme",
  "loading.prepareLanguage": "Wechsle Sprache",
  "loading.done": "Fertig",

  "menu.header": "Menü",
  "menu.version": "Version",

  "player": "Spieler",

  "config.type.prev": "<<",
  "config.type.next": ">>",
  "config.co.prev": "<<",
  "config.co.next": ">>",
  "config.team.next": ">>",
  "config.team.prev": "<<",

  "config.playerCo": "CO",
  "config.playerType": "Typ",
  "config.playerTeam": "Team",

  "config.next": "Spiel Starten",

  "config.player.off": "Frei",
  "config.player.disabled": "-",
  "config.player.co.none": "Kein",
  "config.player.AI": "KI",
  "config.player.human": "Spieler",

  "message.panel.header": "Nachricht",

  "versus.playerconfig": "Spielerkonfiguration",
  "versus.next": "Spielerkonfiguration",
  "versus.mapSelection": "Kartenauswahl",
  "versus.prevMap": "Vorherige Karte",
  "versus.nextMap": "Nächste Karte",

  "error.panel.action": "Spieldaten zurücksetzen?",
  "error.panel.header": "Schwerwiegender Fehler",
  "error.panel.reason": "Grund",
  "error.panel.data": "Daten",
  "error.panel.no": "Nein",
  "error.panel.yes": "Ja",

  "MAIN_MENU_OPTIONS": "Optionen",
  "MAIN_MENU_NETWORK": "Netzwerkspiel",
  "MAIN_MENU_SKIRMISH": "Einzelspiel",
  "MAIN_MENU_TEST_WEATHER": "Wetter-Test",

  "OPTIONS_SFX_VOL_DOWN": "-",
  "OPTIONS_SFX_VOL_UP": "+",
  "OPTIONS_MUSIC_VOL_DOWN": "-",
  "OPTIONS_MUSIC_VOL_UP": "+",
  "OPTIONS_CHECKBOX_ANIMATED_TILES_TEXT": "Animierte Felder",
  "OPTIONS_CHECKBOX_FORCE_TOUCH_TEXT": "Erzwinge Touch-Bedienung",
  "OPTIONS_MENU_CHANGE_KEYBOARD_LAYOUT": "Konfiguriere Tastatur",
  "OPTIONS_MENU_CHANGE_GAMEPAD_LAYOUT": "Konfiguriere Gamepad",
  "OPTIONS_MENU_WIPE_OUT": "Daten zurücksetzen",
  "OPTIONS_MENU_GO_BACK": "Zurück",

  "OPTIONS_WIPE_OUT_TEXT": "Löscht alle Spieldaten. Beim nächsten\nSpielstart werden benötigte Daten erneut geladen.",
  "OPTIONS_WIPE_OUT_NO": "Abbrechen",
  "OPTIONS_WIPE_OUT_YES": "Tu es!",

  "OPTIONS_KEYMAP_RIGHT": "Rechts",
  "OPTIONS_KEYMAP_LEFT": "Links",
  "OPTIONS_KEYMAP_DOWN": "Unten",
  "OPTIONS_KEYMAP_UP": "Oben",
  "OPTIONS_KEYMAP_ACTION": "Aktion",
  "OPTIONS_KEYMAP_CANCEL": "Abbrechen",

  "MAP_SELECT_PAGE_LEFT": "<<",
  "MAP_SELECT_PAGE": "",
  "MAP_SELECT_PAGE_RIGHT": ">>",
  "MENU_BACK": "Zurück",
  "MENU_NEXT": "Weiter",
  "MENU_RIGHT": ">>",
  "MENU_LEFT": "<<",
  "MENU_CONFIGURED_MATCH": "Eigenes Spiel",
  "MENU_FAST_MATCH": "Schnelles Spiel",

  "PLAYER_CONFIG_SLOT1": "Slot 1",
  "PLAYER_CONFIG_SLOT2": "Slot 2",
  "PLAYER_CONFIG_SLOT3": "Slot 3",
  "PLAYER_CONFIG_SLOT4": "Slot 4",

  "PLAYER_CONFIG_NAME": "Name",
  "PLAYER_CONFIG_TYPE": "Typ",
  "PLAYER_CONFIG_TEAM": "Team",
  "PLAYER_CONFIG_CO_A": "Haupt-CO",
  "PLAYER_CONFIG_GAMEMODE": "Spielmodus",

  "VALUE_R": "",
  "VALUE_L": "",
  "VALUE_U": "",
  "VALUE_D": "",
  "VALUE_A": "",
  "VALUE_C": "",

  "co_getStarCost": "Star Kosten",
  "co_getStarCostIncrease": "Star K. Erhö.",
  "co_getStarCostIncreaseSteps": "Star K. Erhö. Stufen",
  "co_enabledCoPower": "Co Powers",
  "fogEnabled": "Nebel des Krieges",
  "daysOfPeace": "Tage des Friedens",
  "weatherMinDays": "Wetter min. Dauer",
  "weatherRandomDays": "Wetter max. Dauer",
  "noUnitsLeftLoose": "Verliere ohne Einheiten",
  "autoSupplyAtTurnStart": "Zugstart Auto-Versorg.",
  "round_dayLimit": "Tage-Limit",
  "unitLimit": "Einheiten-Limit",
  "captureLimit": "Gebäude-Limit",
  "timer_turnTimeLimit": "Zugzeit (Min.)",
  "timer_gameTimeLimit": "Spielzeit (Min.)",

  "OPTIONS_KEYMAP_GOBACK": "Zurück",
  "OPTIONS_KEYMAP_SET": "Setze Tasten",

  "TOOLTIP_1": "Change the keyboard and gamepad settings by selecting\nOptions from the main or in-game menu",
  "TOOLTIP_2": "Activate zooming the map by using the scroll wheel for\nthe mouse, pinching for touch screen, and the in-game menu.",
  "TOOLTIP_3": "Press and hold Cancel over an idle unit to\nsee its attack range.",
  "TOOLTIP_4": "Perform Cancel by right-clicking with mouse,\nor double-tapping for touch screen.",
  "TOOLTIP_5": "Keyboard and game-pad controls can be changed\nvia the Options Menu.",
  "TOOLTIP_6": "Perform Action by lieft-clicking with the mouse\n, or tapping the touch screen.",
  "TOOLTIP_7": "Reporting bugs to the developers can be done\nthrough the Mailing List or the forum.",
  "TOOLTIP_8": "Custom Wars Tactics concept started in January 2009.\nThe original name for the project was called 'Tactic Wars'.",
  "TOOLTIP_9": "Custom Wars Tactics is playable from PC and also from\nmobile devices.",
  "TOOLTIP_10": "Custom Wars Tactics can be played offline in your\nbrowser. (As long you aren't in private browsing mode.)",
  "TOOLTIP_11": "A full desktop counterpart for Custom Wars Tactics\nis being developed. Stay tuned!"
});
*/