cwt.Config.create("weatherMinDays",1,5,1);
cwt.Config.create("weatherRandomDays",0,5,4);
cwt.Config.create("round_dayLimit",0,999,0);
cwt.Config.create("noUnitsLeftLoose",0,1,0);
cwt.Config.create("autoSupplyAtTurnStart",0,1,1);
cwt.Config.create("unitLimit",0,cwt.Player.MAX_UNITS,0,5);
cwt.Config.create("captureLimit",0,cwt.Property.MULTITON_INSTANCES,0);
cwt.Config.create("timer_turnTimeLimit",0,60,0,1);
cwt.Config.create("timer_gameTimeLimit",0,99999,0,5);