var INACTIVE_ID=-1;
var DESELECT_ID=-2;
var ACTIONS_BUFFER_SIZE=200;
var MAX_PLAYER=4;
var MAX_MAP_WIDTH=80;
var MAX_MAP_HEIGHT=60;
var MAX_UNITS_PER_PLAYER=50;
var MAX_PROPERTIES=300;
var MAX_SELECTION_RANGE=15;
var MAX_BUFFER_SIZE=200;
var VERSION="0.3.6";
var DEBUG=true;
var AI_VERSION="DumbBoy v. 0.1 Alpha";
var MOD_PATH="http://192.168.1.26:8000/mod/cwt/";

var EV_FACTORY_TYPE_CHECK = "ev_fac_canBuild";
var EV_FACTORY_TYPE_BUILDED = "ev_fac_builded";
