/**
 * @class
 */
cwt.Sprite = my.Class({

  constructor: function (images, offsetX, offsetY) {
    this.img = images;
    this.ox = offsetX;
    this.oy = offsetY;
    this.overlay = false;
    this.animated = false;
  },

  /**
   *
   * @param state
   * @param {number=} color
   */
  getImageFor: function (state, color) {

  }
});

/**
 *
 * @namespace
 */
cwt.Image = {

  /** @constant */
  STATE_IDLE: 0,

  /** @constant */
  STATE_IDLE_INVERTED: 1,

  /** @constant */
  STATE_RIGHT: 2,

  /** @constant */
  STATE_LEFT: 3,

  /** @constant */
  STATE_UP: 4,

  /** @constant */
  STATE_DOWN: 5,

  /** @constant */
  CODE_STATELESS: 0,

  /** @constant */
  COLOR_RED: 0,

  /** @constant */
  COLOR_GREEN: 1,

  /** @constant */
  COLOR_BLUE: 2,

  /** @constant */
  COLOR_YELLOW: 3,

  /** @constant */
  COLOR_BLACK_MASK: 4,

  /** @constant */
  COLOR_NEUTRAL: 5,

  /** @constant */
  COLOR_NONE: 0,

  /**
   * Represents the current loading process. The graphics will be generated by
   * a web worker in the main menu. A player can configure a game session during
   * the loading process. Normally the image processing process will be done
   * before the configuration is ready. If the image process is not ready, then
   * the game will go into a loading screen before entering the game screen.
   */
  background_image_loading_complete: false,

  /**
   * @type {Array.<cwt.Sprite>}
   */
  sprites: {}

};